  
---
# file: roles/cds/tasks/main.yml

- name: Create a directory if it does not exist
  file:
    path: /home/ubuntu/cds/tools/smtpmock
    state: directory
    mode: '0755'
- name: create /home/ubuntu/cds/boot.sh
  template:
    src:  boot.sh.j2
    dest: /home/ubuntu/cds/boot.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'
- name: Run /home/ubuntu/cds/boot.sh
  shell: "bash /home/ubuntu/cds/boot.sh > boot.sh.log"
  args:
    chdir: /home/ubuntu/cds/
    creates: /home/ubuntu/cds/cdsctl
